# -*- coding: utf-8 -*-
"""Data visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuwiH_H7f_Edt8e9baODz3ha5ajK-GDF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/titanic dataset.csv')
print(df.head)

print(df.info)

print(df.describe())

print(df.isnull().sum)

#handling missing values
df['Age'].fillna(df['Age'].median(), inplace = True)

print(df.head)

#dopping unnessary  columns
df.drop(['Cabin', 'Ticket', 'Name', 'PassengerId', 'Fare', 'Embarked'], axis=1, inplace=True)

print(df.head)

#converting sex to numerical
df['Sex'].map({'male':1,'female':0})

print(df.isnull().sum())

#Exploratory Data Analysis
sns.countplot(x='Survived', hue='Sex', data=df)
plt.show()

sns.countplot(x='Survived', hue='Pclass',data=df)

sns.histplot(df, x='Age',hue='Survived',kde=True)

sns.boxplot(x='Pclass', y='Age', data=df)

df['Sex'] = df['Sex'].map({'male':1,'female':0})
correlation_matrix=df.corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')